export interface Country {
  value: string;
  map: string;
  phonevalue: number;
  label: string;
}

export const countries: Country[] = [
  {
    value: "AF",
    map: "🇦🇫",
    phonevalue: 93,
    label: "Afghanistan",
  },
  {
    value: "AL",
    map: "🇦🇱",
    phonevalue: 355,
    label: "Albania",
  },
  {
    value: "DZ",
    map: "🇩🇿",
    phonevalue: 213,
    label: "Algeria",
  },
  {
    value: "AS",
    map: "🇦🇸",
    phonevalue: 1684,
    label: "American Samoa",
  },
  {
    value: "AD",
    map: "🇦🇩",
    phonevalue: 376,
    label: "Andorra",
  },
  {
    value: "AO",
    map: "🇦🇴",
    phonevalue: 244,
    label: "Angola",
  },
  {
    value: "AI",
    map: "🇦🇮",
    phonevalue: 1264,
    label: "Anguilla",
  },
  {
    value: "AQ",
    map: "🇦🇶",
    phonevalue: 0,
    label: "Antarctica",
  },
  {
    value: "AR",
    map: "🇦🇷",
    phonevalue: 54,
    label: "Argentina",
  },
  {
    value: "AM",
    map: "🇦🇲",
    phonevalue: 374,
    label: "Armenia",
  },
  {
    value: "AW",
    map: "🇦🇼",
    phonevalue: 297,
    label: "Aruba",
  },
  {
    value: "AU",
    map: "🇦🇺",
    phonevalue: 61,
    label: "Australia",
  },
  {
    value: "AT",
    map: "🇦🇹",
    phonevalue: 43,
    label: "Austria",
  },
  {
    value: "AZ",
    map: "🇦🇿",
    phonevalue: 994,
    label: "Azerbaijan",
  },
  {
    value: "BH",
    map: "🇧🇭",
    phonevalue: 973,
    label: "Bahrain",
  },
  {
    value: "BD",
    map: "🇧🇩",
    phonevalue: 880,
    label: "Bangladesh",
  },
  {
    value: "BB",
    map: "🇧🇧",
    phonevalue: 1246,
    label: "Barbados",
  },
  {
    value: "BY",
    map: "🇧🇾",
    phonevalue: 375,
    label: "Belarus",
  },
  {
    value: "BE",
    map: "🇧🇪",
    phonevalue: 32,
    label: "Belgium",
  },
  {
    value: "BZ",
    map: "🇧🇿",
    phonevalue: 501,
    label: "Belize",
  },
  {
    value: "BJ",
    map: "🇧🇯",
    phonevalue: 229,
    label: "Benin",
  },
  {
    value: "BM",
    map: "🇧🇲",
    phonevalue: 1441,
    label: "Bermuda",
  },
  {
    value: "BT",
    map: "🇧🇹",
    phonevalue: 975,
    label: "Bhutan",
  },
  {
    value: "BO",
    map: "🇧🇴",
    phonevalue: 591,
    label: "Bolivia",
  },
  {
    value: "BW",
    map: "🇧🇼",
    phonevalue: 267,
    label: "Botswana",
  },
  {
    value: "BV",
    map: "🇧🇻",
    phonevalue: 0,
    label: "Bouvet Island",
  },
  {
    value: "BR",
    map: "🇧🇷",
    phonevalue: 55,
    label: "Brazil",
  },
  {
    value: "IO",
    map: "🇮🇴",
    phonevalue: 246,
    label: "British Indian Ocean Territory",
  },
  {
    value: "BN",
    map: "🇧🇳",
    phonevalue: 673,
    label: "Brunei",
  },
  {
    value: "BG",
    map: "🇧🇬",
    phonevalue: 359,
    label: "Bulgaria",
  },
  {
    value: "BF",
    map: "🇧🇫",
    phonevalue: 226,
    label: "Burkina Faso",
  },
  {
    value: "BI",
    map: "🇧🇮",
    phonevalue: 257,
    label: "Burundi",
  },
  {
    value: "KH",
    map: "🇰🇭",
    phonevalue: 855,
    label: "Cambodia",
  },
  {
    value: "CM",
    map: "🇨🇲",
    phonevalue: 237,
    label: "Cameroon",
  },
  {
    value: "CA",
    map: "🇨🇦",
    phonevalue: 1,
    label: "Canada",
  },
  {
    value: "CV",
    map: "🇨🇻",
    phonevalue: 238,
    label: "Cape Verde",
  },
  {
    value: "KY",
    map: "🇰🇾",
    phonevalue: 1345,
    label: "Cayman Islands",
  },
  {
    value: "CF",
    map: "🇨🇫",
    phonevalue: 236,
    label: "Central African Republic",
  },
  {
    value: "TD",
    map: "🇹🇩",
    phonevalue: 235,
    label: "Chad",
  },
  {
    value: "CL",
    map: "🇨🇱",
    phonevalue: 56,
    label: "Chile",
  },
  {
    value: "CN",
    map: "🇨🇳",
    phonevalue: 86,
    label: "China",
  },
  {
    value: "CX",
    map: "🇨🇽",
    phonevalue: 61,
    label: "Christmas Island",
  },
  {
    value: "CC",
    map: "🇨🇨",
    phonevalue: 672,
    label: "Cocos (Keeling) Islands",
  },
  {
    value: "CO",
    map: "🇨🇴",
    phonevalue: 57,
    label: "Colombia",
  },
  {
    value: "KM",
    map: "🇰🇲",
    phonevalue: 269,
    label: "Comoros",
  },
  {
    value: "CK",
    map: "🇨🇰",
    phonevalue: 682,
    label: "Cook Islands",
  },
  {
    value: "CR",
    map: "🇨🇷",
    phonevalue: 506,
    label: "Costa Rica",
  },
  {
    value: "CU",
    map: "🇨🇺",
    phonevalue: 53,
    label: "Cuba",
  },
  {
    value: "CY",
    map: "🇨🇾",
    phonevalue: 357,
    label: "Cyprus",
  },
  {
    value: "DK",
    map: "🇩🇰",
    phonevalue: 45,
    label: "Denmark",
  },
  {
    value: "DJ",
    map: "🇩🇯",
    phonevalue: 253,
    label: "Djibouti",
  },
  {
    value: "DM",
    map: "🇩🇲",
    phonevalue: 1767,
    label: "Dominica",
  },
  {
    value: "DO",
    map: "🇩🇴",
    phonevalue: 1809,
    label: "Dominican Republic",
  },
  {
    value: "EC",
    map: "🇪🇨",
    phonevalue: 593,
    label: "Ecuador",
  },
  {
    value: "EG",
    map: "🇪🇬",
    phonevalue: 20,
    label: "Egypt",
  },
  {
    value: "SV",
    map: "🇸🇻",
    phonevalue: 503,
    label: "El Salvador",
  },
  {
    value: "GQ",
    map: "🇬🇶",
    phonevalue: 240,
    label: "Equatorial Guinea",
  },
  {
    value: "ER",
    map: "🇪🇷",
    phonevalue: 291,
    label: "Eritrea",
  },
  {
    value: "EE",
    map: "🇪🇪",
    phonevalue: 372,
    label: "Estonia",
  },
  {
    value: "ET",
    map: "🇪🇹",
    phonevalue: 251,
    label: "Ethiopia",
  },
  {
    value: "FK",
    map: "🇫🇰",
    phonevalue: 500,
    label: "Falkland Islands",
  },
  {
    value: "FO",
    map: "🇫🇴",
    phonevalue: 298,
    label: "Faroe Islands",
  },
  {
    value: "FI",
    map: "🇫🇮",
    phonevalue: 358,
    label: "Finland",
  },
  {
    value: "FR",
    map: "🇫🇷",
    phonevalue: 33,
    label: "France",
  },
  {
    value: "GF",
    map: "🇬🇫",
    phonevalue: 594,
    label: "French Guiana",
  },
  {
    value: "PF",
    map: "🇵🇫",
    phonevalue: 689,
    label: "French Polynesia",
  },
  {
    value: "TF",
    map: "🇹🇫",
    phonevalue: 0,
    label: "French Southern Territories",
  },
  {
    value: "GA",
    map: "🇬🇦",
    phonevalue: 241,
    label: "Gabon",
  },
  {
    value: "GE",
    map: "🇬🇪",
    phonevalue: 995,
    label: "Georgia",
  },
  {
    value: "DE",
    map: "🇩🇪",
    phonevalue: 49,
    label: "Germany",
  },
  {
    value: "GH",
    map: "🇬🇭",
    phonevalue: 233,
    label: "Ghana",
  },
  {
    value: "GI",
    map: "🇬🇮",
    phonevalue: 350,
    label: "Gibraltar",
  },
  {
    value: "GR",
    map: "🇬🇷",
    phonevalue: 30,
    label: "Greece",
  },
  {
    value: "GL",
    map: "🇬🇱",
    phonevalue: 299,
    label: "Greenland",
  },
  {
    value: "GD",
    map: "🇬🇩",
    phonevalue: 1473,
    label: "Grenada",
  },
  {
    value: "GP",
    map: "🇬🇵",
    phonevalue: 590,
    label: "Guadeloupe",
  },
  {
    value: "GU",
    map: "🇬🇺",
    phonevalue: 1671,
    label: "Guam",
  },
  {
    value: "GT",
    map: "🇬🇹",
    phonevalue: 502,
    label: "Guatemala",
  },
  {
    value: "GN",
    map: "🇬🇳",
    phonevalue: 224,
    label: "Guinea",
  },
  {
    value: "GW",
    map: "🇬🇼",
    phonevalue: 245,
    label: "Guinea-Bissau",
  },
  {
    value: "GY",
    map: "🇬🇾",
    phonevalue: 592,
    label: "Guyana",
  },
  {
    value: "HT",
    map: "🇭🇹",
    phonevalue: 509,
    label: "Haiti",
  },
  {
    value: "HN",
    map: "🇭🇳",
    phonevalue: 504,
    label: "Honduras",
  },
  {
    value: "HU",
    map: "🇭🇺",
    phonevalue: 36,
    label: "Hungary",
  },
  {
    value: "IS",
    map: "🇮🇸",
    phonevalue: 354,
    label: "Iceland",
  },
  {
    value: "IN",
    map: "🇮🇳",
    phonevalue: 91,
    label: "India",
  },
  {
    value: "ID",
    map: "🇮🇩",
    phonevalue: 62,
    label: "Indonesia",
  },
  {
    value: "IR",
    map: "🇮🇷",
    phonevalue: 98,
    label: "Iran",
  },
  {
    value: "IQ",
    map: "🇮🇶",
    phonevalue: 964,
    label: "Iraq",
  },
  {
    value: "IE",
    map: "🇮🇪",
    phonevalue: 353,
    label: "Ireland",
  },
  {
    value: "IL",
    map: "🇮🇱",
    phonevalue: 972,
    label: "Israel",
  },
  {
    value: "IT",
    map: "🇮🇹",
    phonevalue: 39,
    label: "Italy",
  },
  {
    value: "JM",
    map: "🇯🇲",
    phonevalue: 1876,
    label: "Jamaica",
  },
  {
    value: "JP",
    map: "🇯🇵",
    phonevalue: 81,
    label: "Japan",
  },
  {
    value: "JO",
    map: "🇯🇴",
    phonevalue: 962,
    label: "Jordan",
  },
  {
    value: "KZ",
    map: "🇰🇿",
    phonevalue: 7,
    label: "Kazakhstan",
  },
  {
    value: "KE",
    map: "🇰🇪",
    phonevalue: 254,
    label: "Kenya",
  },
  {
    value: "KI",
    map: "🇰🇮",
    phonevalue: 686,
    label: "Kiribati",
  },
  {
    value: "KW",
    map: "🇰🇼",
    phonevalue: 965,
    label: "Kuwait",
  },
  {
    value: "KG",
    map: "🇰🇬",
    phonevalue: 996,
    label: "Kyrgyzstan",
  },
  {
    value: "LA",
    map: "🇱🇦",
    phonevalue: 856,
    label: "Laos",
  },
  {
    value: "LV",
    map: "🇱🇻",
    phonevalue: 371,
    label: "Latvia",
  },
  {
    value: "LB",
    map: "🇱🇧",
    phonevalue: 961,
    label: "Lebanon",
  },
  {
    value: "LS",
    map: "🇱🇸",
    phonevalue: 266,
    label: "Lesotho",
  },
  {
    value: "LR",
    map: "🇱🇷",
    phonevalue: 231,
    label: "Liberia",
  },
  {
    value: "LY",
    map: "🇱🇾",
    phonevalue: 218,
    label: "Libya",
  },
  {
    value: "LI",
    map: "🇱🇮",
    phonevalue: 423,
    label: "Liechtenstein",
  },
  {
    value: "LT",
    map: "🇱🇹",
    phonevalue: 370,
    label: "Lithuania",
  },
  {
    value: "LU",
    map: "🇱🇺",
    phonevalue: 352,
    label: "Luxembourg",
  },
  {
    value: "MK",
    map: "🇲🇰",
    phonevalue: 389,
    label: "Macedonia",
  },
  {
    value: "MG",
    map: "🇲🇬",
    phonevalue: 261,
    label: "Madagascar",
  },
  {
    value: "MW",
    map: "🇲🇼",
    phonevalue: 265,
    label: "Malawi",
  },
  {
    value: "MY",
    map: "🇲🇾",
    phonevalue: 60,
    label: "Malaysia",
  },
  {
    value: "MV",
    map: "🇲🇻",
    phonevalue: 960,
    label: "Maldives",
  },
  {
    value: "ML",
    map: "🇲🇱",
    phonevalue: 223,
    label: "Mali",
  },
  {
    value: "MT",
    map: "🇲🇹",
    phonevalue: 356,
    label: "Malta",
  },
  {
    value: "MH",
    map: "🇲🇭",
    phonevalue: 692,
    label: "Marshall Islands",
  },
  {
    value: "MQ",
    map: "🇲🇶",
    phonevalue: 596,
    label: "Martinique",
  },
  {
    value: "MR",
    map: "🇲🇷",
    phonevalue: 222,
    label: "Mauritania",
  },
  {
    value: "MU",
    map: "🇲🇺",
    phonevalue: 230,
    label: "Mauritius",
  },
  {
    value: "YT",
    map: "🇾🇹",
    phonevalue: 269,
    label: "Mayotte",
  },
  {
    value: "MX",
    map: "🇲🇽",
    phonevalue: 52,
    label: "Mexico",
  },
  {
    value: "FM",
    map: "🇫🇲",
    phonevalue: 691,
    label: "Micronesia",
  },
  {
    value: "MD",
    map: "🇲🇩",
    phonevalue: 373,
    label: "Moldova",
  },
  {
    value: "MC",
    map: "🇲🇨",
    phonevalue: 377,
    label: "Monaco",
  },
  {
    value: "MN",
    map: "🇲🇳",
    phonevalue: 976,
    label: "Mongolia",
  },
  {
    value: "MS",
    map: "🇲🇸",
    phonevalue: 1664,
    label: "Montserrat",
  },
  {
    value: "MA",
    map: "🇲🇦",
    phonevalue: 212,
    label: "Morocco",
  },
  {
    value: "MZ",
    map: "🇲🇿",
    phonevalue: 258,
    label: "Mozambique",
  },
  {
    value: "NA",
    map: "🇳🇦",
    phonevalue: 264,
    label: "Namibia",
  },
  {
    value: "NR",
    map: "🇳🇷",
    phonevalue: 674,
    label: "Nauru",
  },
  {
    value: "NP",
    map: "🇳🇵",
    phonevalue: 977,
    label: "Nepal",
  },
  {
    value: "NC",
    map: "🇳🇨",
    phonevalue: 687,
    label: "New Caledonia",
  },
  {
    value: "NZ",
    map: "🇳🇿",
    phonevalue: 64,
    label: "New Zealand",
  },
  {
    value: "NI",
    map: "🇳🇮",
    phonevalue: 505,
    label: "Nicaragua",
  },
  {
    value: "NE",
    map: "🇳🇪",
    phonevalue: 227,
    label: "Niger",
  },
  {
    value: "NG",
    map: "🇳🇬",
    phonevalue: 234,
    label: "Nigeria",
  },
  {
    value: "NU",
    map: "🇳🇺",
    phonevalue: 683,
    label: "Niue",
  },
  {
    value: "NF",
    map: "🇳🇫",
    phonevalue: 672,
    label: "Norfolk Island",
  },
  {
    value: "MP",
    map: "🇲🇵",
    phonevalue: 1670,
    label: "Northern Mariana Islands",
  },
  {
    value: "NO",
    map: "🇳🇴",
    phonevalue: 47,
    label: "Norway",
  },
  {
    value: "OM",
    map: "🇴🇲",
    phonevalue: 968,
    label: "Oman",
  },
  {
    value: "PK",
    map: "🇵🇰",
    phonevalue: 92,
    label: "Pakistan",
  },
  {
    value: "PW",
    map: "🇵🇼",
    phonevalue: 680,
    label: "Palau",
  },
  {
    value: "PA",
    map: "🇵🇦",
    phonevalue: 507,
    label: "Panama",
  },
  {
    value: "PY",
    map: "🇵🇾",
    phonevalue: 595,
    label: "Paraguay",
  },
  {
    value: "PE",
    map: "🇵🇪",
    phonevalue: 51,
    label: "Peru",
  },
  {
    value: "PH",
    map: "🇵🇭",
    phonevalue: 63,
    label: "Philippines",
  },
  {
    value: "PL",
    map: "🇵🇱",
    phonevalue: 48,
    label: "Poland",
  },
  {
    value: "PT",
    map: "🇵🇹",
    phonevalue: 351,
    label: "Portugal",
  },
  {
    value: "PR",
    map: "🇵🇷",
    phonevalue: 1787,
    label: "Puerto Rico",
  },
  {
    value: "QA",
    map: "🇶🇦",
    phonevalue: 974,
    label: "Qatar",
  },
  {
    value: "RO",
    map: "🇷🇴",
    phonevalue: 40,
    label: "Romania",
  },
  {
    value: "RU",
    map: "🇷🇺",
    phonevalue: 70,
    label: "Russia",
  },
  {
    value: "RW",
    map: "🇷🇼",
    phonevalue: 250,
    label: "Rwanda",
  },
  {
    value: "WS",
    map: "🇼🇸",
    phonevalue: 684,
    label: "Samoa",
  },
  {
    value: "SM",
    map: "🇸🇲",
    phonevalue: 378,
    label: "San Marino",
  },
  {
    value: "SA",
    map: "🇸🇦",
    phonevalue: 966,
    label: "Saudi Arabia",
  },
  {
    value: "SN",
    map: "🇸🇳",
    phonevalue: 221,
    label: "Senegal",
  },
  {
    value: "RS",
    map: "🇷🇸",
    phonevalue: 381,
    label: "Serbia",
  },
  {
    value: "SC",
    map: "🇸🇨",
    phonevalue: 248,
    label: "Seychelles",
  },
  {
    value: "SL",
    map: "🇸🇱",
    phonevalue: 232,
    label: "Sierra Leone",
  },
  {
    value: "SG",
    map: "🇸🇬",
    phonevalue: 65,
    label: "Singapore",
  },
  {
    value: "SK",
    map: "🇸🇰",
    phonevalue: 421,
    label: "Slovakia",
  },
  {
    value: "SI",
    map: "🇸🇮",
    phonevalue: 386,
    label: "Slovenia",
  },
  {
    value: "SB",
    map: "🇸🇧",
    phonevalue: 677,
    label: "Solomon Islands",
  },
  {
    value: "SO",
    map: "🇸🇴",
    phonevalue: 252,
    label: "Somalia",
  },
  {
    value: "ZA",
    map: "🇿🇦",
    phonevalue: 27,
    label: "South Africa",
  },
  {
    value: "SS",
    map: "🇸🇸",
    phonevalue: 211,
    label: "South Sudan",
  },
  {
    value: "ES",
    map: "🇪🇸",
    phonevalue: 34,
    label: "Spain",
  },
  {
    value: "LK",
    map: "🇱🇰",
    phonevalue: 94,
    label: "Sri Lanka",
  },
  {
    value: "SD",
    map: "🇸🇩",
    phonevalue: 249,
    label: "Sudan",
  },
  {
    value: "SR",
    map: "🇸🇷",
    phonevalue: 597,
    label: "Suriname",
  },
  {
    value: "SZ",
    map: "🇸🇿",
    phonevalue: 268,
    label: "Swaziland",
  },
  {
    value: "SE",
    map: "🇸🇪",
    phonevalue: 46,
    label: "Sweden",
  },
  {
    value: "CH",
    map: "🇨🇭",
    phonevalue: 41,
    label: "Switzerland",
  },
  {
    value: "SY",
    map: "🇸🇾",
    phonevalue: 963,
    label: "Syria",
  },
  {
    value: "TW",
    map: "🇹🇼",
    phonevalue: 886,
    label: "Taiwan",
  },
  {
    value: "TJ",
    map: "🇹🇯",
    phonevalue: 992,
    label: "Tajikistan",
  },
  {
    value: "TZ",
    map: "🇹🇿",
    phonevalue: 255,
    label: "Tanzania",
  },
  {
    value: "TH",
    map: "🇹🇭",
    phonevalue: 66,
    label: "Thailand",
  },
  {
    value: "TG",
    map: "🇹🇬",
    phonevalue: 228,
    label: "Togo",
  },
  {
    value: "TK",
    map: "🇹🇰",
    phonevalue: 690,
    label: "Tokelau",
  },
  {
    value: "TO",
    map: "🇹🇴",
    phonevalue: 676,
    label: "Tonga",
  },
  {
    value: "TN",
    map: "🇹🇳",
    phonevalue: 216,
    label: "Tunisia",
  },
  {
    value: "TR",
    map: "🇹🇷",
    phonevalue: 90,
    label: "Turkey",
  },
  {
    value: "TM",
    map: "🇹🇲",
    phonevalue: 7370,
    label: "Turkmenistan",
  },
  {
    value: "TV",
    map: "🇹🇻",
    phonevalue: 688,
    label: "Tuvalu",
  },
  {
    value: "UG",
    map: "🇺🇬",
    phonevalue: 256,
    label: "Uganda",
  },
  {
    value: "UA",
    map: "🇺🇦",
    phonevalue: 380,
    label: "Ukraine",
  },
  {
    value: "AE",
    map: "🇦🇪",
    phonevalue: 971,
    label: "United Arab Emirates",
  },
  {
    value: "GB",
    map: "🇬🇧",
    phonevalue: 44,
    label: "United Kingdom",
  },
  {
    value: "US",
    map: "🇺🇸",
    phonevalue: 1,
    label: "United States",
  },
  {
    value: "UY",
    map: "🇺🇾",
    phonevalue: 598,
    label: "Uruguay",
  },
  {
    value: "UZ",
    map: "🇺🇿",
    phonevalue: 998,
    label: "Uzbekistan",
  },
  {
    value: "VU",
    map: "🇻🇺",
    phonevalue: 678,
    label: "Vanuatu",
  },
  {
    value: "VE",
    map: "🇻🇪",
    phonevalue: 58,
    label: "Venezuela",
  },
  {
    value: "VN",
    map: "🇻🇳",
    phonevalue: 84,
    label: "Vietnam",
  },
  {
    value: "EH",
    map: "🇪🇭",
    phonevalue: 212,
    label: "Western Sahara",
  },
  {
    value: "YE",
    map: "🇾🇪",
    phonevalue: 967,
    label: "Yemen",
  },
  {
    value: "ZM",
    map: "🇿🇲",
    phonevalue: 260,
    label: "Zambia",
  },
  {
    value: "ZW",
    map: "🇿🇼",
    phonevalue: 26,
    label: "Zimbabwe",
  },
];
