export const orgName = "Swim UK";
export const orgLogo = "./src/assets/logo.png";

export const orgColours = {
  primary: "#e4f7fb",
  primary_text: "#005da2",
  secondary: "#005da2",
  secondary_text: "#ffffff",
  interactive: "#005da2",
};

export const orgBanners = [
  {
    img: "./src/assets/banner-1.jpg",
    title: "Crash Courses",
    description:
      "Suitable for young swimmers, we concentrate on improving confidence and technique. Prices start from £30 a session.",
    link: "/BubbleTheSeahorse",
  },
  {
    img: "./src/assets/banner-2.jpg",
    title: "24th May - English County Championships",
    description:
      "Get your tickets for this year's championship to witness the highest level of swimming in the UK. Adult tickets are £15, while children's tickets cost £5.",
    link: "/BubbleTheSeahorse",
  },
  {
    img: "./src/assets/banner-3.jpg",
    title: "Buy your swimming gear today!",
    description:
      "We have an excellent choice of swimming equipment for all ages, including new Speedo Anti Fog goggles.",
    link: "/BubbleTheSeahorse",
  },
];

export const orgTiles = [
  {
    img: "./src/assets/6f2e0f06-8900-4dc0-981a-0259989f1871.jpeg",
    title: "Adult and Child Lessons",
    link: "/AdultChildLessons",
  },
  {
    img: "./src/assets/788667ca-19eb-4818-88f2-8b895dadcdf2.jpeg",
    title: "Independent Children's Lessons",
    link: "/AdultChildLessons",
  },
  {
    img: "./src/assets/53602522-6ebd-4ce5-83a1-4ea35f8f1efe.jpeg",
    title: "Adult Lessons",
    link: "/AdultChildLessons",
  },
  {
    img: "./src/assets/58484fa4-ef77-43c0-9c6f-34d6a47be27f.jpeg",
    title: "Private Lessons",
    link: "/AdultChildLessons",
  },
  {
    img: "./src/assets/da5cce7f-faba-46c0-b160-e0dad0d5fbb7.jpeg",
    title: "Adult and Child Lessons",
    link: "/AdultChildLessons",
  },
  {
    img: "./src/assets/292eec5b-ab54-41be-83ce-e70f00257b41.jpeg",
    title: "Independent Children's Lessons",
    link: "/AdultChildLessons",
  },
  {
    img: "./src/assets/a3ec16f6-f8ff-40d9-8f47-3d15fa85d932.jpeg",
    title: "Adult Lessons",
    link: "/AdultChildLessons",
  },
  {
    img: "./src/assets/540d3059-e4e3-4ef5-a516-c24f1bed3c50.jpeg",
    title: "Private Lessons",
    link: "/AdultChildLessons",
  },
  {
    img: "./src/assets/06e8f09a-6232-4246-b75d-65739ccaade2.jpeg",
    title: "Crash Courses",
    link: "/AdultChildLessons",
  },
];

export const orgEvents = {
  Monday: [
    {
      img: "./src/assets/turtle.jpg",
      title: "Smiley the Turtle",
      description: "3-4 years",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "09:30",
      endTime: "10:00",
      price: "£16.00",
      colour: "emerald",
      productColour: "emerald",
      productGroup: "Adult and Child Lessons",
    },
    {
      img: "./src/assets/jelly.jpg",
      title: "Jelly the Jellyfish",
      description: "2-3 years",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "10:00",
      endTime: "10:30",
      price: "£16.00",
      colour: "violet",
      productColour: "emerald",
      productGroup: "Adult and Child Lessons",
    },
    {
      img: "./src/assets/jelly.jpg",
      title: "Jelly the Jellyfish",
      description: "2-3 years",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "10:30",
      endTime: "11:00",
      price: "£16.00",
      colour: "violet",
      productColour: "emerald",
      productGroup: "Adult and Child Lessons",
    },
    {
      img: "./src/assets/crab.jpg",
      title: "Snappy the Crab",
      description: "18-24 months",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "11:00",
      endTime: "11:30",
      price: "£16.00",
      colour: "red",
      productColour: "emerald",
      productGroup: "Adult and Child Lessons",
    },
    {
      img: "./src/assets/daf56b3e-5501-4f6d-8927-ce45adf67f1d.jpeg",
      title: "Stage 1",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "11:30",
      endTime: "12:00",
      price: "19.50",
      colour: "emerald",
      productColour: "blue",
      productGroup: "Independent Children's Lessons",
    },
    {
      img: "./src/assets/starfish.jpg",
      title: "Twinkle The Starfish",
      description: "6-12 months",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "12:00",
      endTime: "12:30",
      price: "£16.00",
      colour: "pink",
      productColour: "emerald",
      productGroup: "Adult and Child Lessons",
    },
    {
      img: "./src/assets/crab.jpg",
      title: "Snappy the Crab",
      description: "18-24 months",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "12:45",
      endTime: "13:15",
      price: "£16.00",
      colour: "red",
      productColour: "emerald",
      productGroup: "Adult and Child Lessons",
    },
    {
      img: "./src/assets/daf56b3e-5501-4f6d-8927-ce45adf67f1d.jpeg",
      title: "Stage 1",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "13:15",
      endTime: "13:45",
      price: "19.50",
      colour: "emerald",
      productColour: "blue",
      productGroup: "Independent Children's Lessons",
    },
    {
      img: "./src/assets/daf56b3e-5501-4f6d-8927-ce45adf67f1d.jpeg",
      title: "Stage 2",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "15:00",
      endTime: "15:30",
      price: "19.50",
      colour: "emerald",
      productColour: "blue",
      productGroup: "Independent Children's Lessons",
    },
    {
      img: "./src/assets/daf56b3e-5501-4f6d-8927-ce45adf67f1d.jpeg",
      title: "Stage 4",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "15:30",
      endTime: "16:00",
      price: "16.00",
      colour: "emerald",
      productColour: "blue",
      productGroup: "Independent Children's Lessons",
    },
    {
      img: "./src/assets/daf56b3e-5501-4f6d-8927-ce45adf67f1d.jpeg",
      title: "Stage 3",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "16:00",
      endTime: "16:30",
      price: "16.00",
      colour: "emerald",
      productColour: "blue",
      productGroup: "Independent Children's Lessons",
    },
    {
      img: "./src/assets/daf56b3e-5501-4f6d-8927-ce45adf67f1d.jpeg",
      title: "Stage 5",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "16:30",
      endTime: "17:00",
      price: "16.00",
      colour: "emerald",
      productColour: "blue",
      productGroup: "Independent Children's Lessons",
    },
    {
      img: "./src/assets/daf56b3e-5501-4f6d-8927-ce45adf67f1d.jpeg",
      title: "Stage 3",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "17:00",
      endTime: "17:30",
      price: "16.00",
      colour: "emerald",
      productColour: "blue",
      productGroup: "Independent Children's Lessons",
    },
    {
      img: "./src/assets/daf56b3e-5501-4f6d-8927-ce45adf67f1d.jpeg",
      title: "Stage 4",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "17:30",
      endTime: "18:00",
      price: "16.00",
      colour: "emerald",
      productColour: "blue",
      productGroup: "Independent Children's Lessons",
    },
    {
      img: "./src/assets/daf56b3e-5501-4f6d-8927-ce45adf67f1d.jpeg",
      title: "Stage 2",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "18:00",
      endTime: "18:30",
      price: "19.50",
      colour: "emerald",
      productColour: "blue",
      productGroup: "Independent Children's Lessons",
    },
    {
      img: "./src/assets/daf56b3e-5501-4f6d-8927-ce45adf67f1d.jpeg",
      title: "Stage 3",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "18:30",
      endTime: "19:00",
      price: "16.00",
      colour: "emerald",
      productColour: "blue",
      productGroup: "Independent Children's Lessons",
    },
    {
      img: "./src/assets/daf56b3e-5501-4f6d-8927-ce45adf67f1d.jpeg",
      title: "Stage 5",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "19:00",
      endTime: "19:30",
      price: "16.00",
      colour: "emerald",
      productColour: "blue",
      productGroup: "Independent Children's Lessons",
    },
    {
      img: "./src/assets/37597dfa-bf0b-4ed4-a623-0c8cb6b797f5.jpeg",
      title: "Intermediate",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "19:30",
      endTime: "20:00",
      price: "25.00",
      colour: "emerald",
      productColour: "amber",
      productGroup: "Adult Lessons",
    },
  ],
  Tuesday: [
    {
      img: "./src/assets/daf56b3e-5501-4f6d-8927-ce45adf67f1d.jpeg",
      title: "Stage 2",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "10:30",
      endTime: "11:00",
      price: "19.50",
      colour: "emerald",
      productColour: "blue",
      productGroup: "Independent Children's Lessons",
    },
    {
      img: "./src/assets/daf56b3e-5501-4f6d-8927-ce45adf67f1d.jpeg",
      title: "Stage 1",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "11:00",
      endTime: "11:30",
      price: "19.50",
      colour: "emerald",
      productColour: "blue",
      productGroup: "Independent Children's Lessons",
    },
    {
      img: "./src/assets/seahorse.jpg",
      title: "Bubble the Seahorse",
      description: "12-18 months",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "11:30",
      endTime: "12:00",
      price: "£16.00",
      colour: "indigo",
      productColour: "emerald",
      productGroup: "Adult and Child Lessons",
    },
    {
      img: "./src/assets/dolphin.jpg",
      title: "Danny the Dolphin (SEND)",
      description: "4-5 years",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "17:30",
      endTime: "18:00",
      price: "£16.00",
      colour: "sky",
      productColour: "emerald",
      productGroup: "Adult and Child Lessons",
    },
    {
      img: "./src/assets/dolphin.jpg",
      title: "Danny the Dolphin (SEND)",
      description: "4-5 years",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "18:00",
      endTime: "18:30",
      price: "£16.00",
      colour: "sky",
      productColour: "emerald",
      productGroup: "Adult and Child Lessons",
    },
  ],
  Wednesday: [
    {
      img: "./src/assets/starfish.jpg",
      title: "Twinkle The Starfish",
      description: "6-12 months",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "09:00",
      endTime: "09:30",
      price: "£16.00",
      colour: "pink",
      productColour: "emerald",
      productGroup: "Adult and Child Lessons",
    },
    {
      img: "./src/assets/jelly.jpg",
      title: "Jelly the Jellyfish",
      description: "2-3 years",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "10:00",
      endTime: "10:30",
      price: "£16.00",
      colour: "violet",
      productColour: "emerald",
      productGroup: "Adult and Child Lessons",
    },
    {
      img: "./src/assets/starfish.jpg",
      title: "Twinkle The Starfish",
      description: "6-12 months",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "11:00",
      endTime: "11:30",
      price: "£16.00",
      colour: "pink",
      productColour: "emerald",
      productGroup: "Adult and Child Lessons",
    },
    {
      img: "./src/assets/seahorse.jpg",
      title: "Bubble the Seahorse",
      description: "12-18 months",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "11:30",
      endTime: "12:00",
      price: "£16.00",
      colour: "indigo",
      productColour: "emerald",
      productGroup: "Adult and Child Lessons",
    },
    {
      img: "./src/assets/starfish.jpg",
      title: "Twinkle The Starfish",
      description: "6-12 months",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "14:30",
      endTime: "15:00",
      price: "£16.00",
      colour: "pink",
      productColour: "emerald",
      productGroup: "Adult and Child Lessons",
    },
    {
      img: "./src/assets/crab.jpg",
      title: "Snappy the Crab",
      description: "18-24 months",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "15:00",
      endTime: "15:30",
      price: "£16.00",
      colour: "red",
      productColour: "emerald",
      productGroup: "Adult and Child Lessons",
    },
  ],
  Thursday: [
    {
      img: "./src/assets/jelly.jpg",
      title: "Jelly the Jellyfish",
      description: "2-3 years",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "10:00",
      endTime: "10:30",
      price: "£16.00",
      colour: "violet",
      productColour: "emerald",
      productGroup: "Adult and Child Lessons",
    },
    {
      img: "./src/assets/Clown.jpg",
      title: "Carl the Clownfish",
      description: "3-6 months",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "10:30",
      endTime: "11:00",
      price: "£16.00",
      colour: "orange",
      productColour: "emerald",
      productGroup: "Adult and Child Lessons",
    },
    {
      img: "./src/assets/seahorse.jpg",
      title: "Bubble the Seahorse",
      description: "12-18 months",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "11:00",
      endTime: "11:30",
      price: "£16.00",
      colour: "indigo",
      productColour: "emerald",
      productGroup: "Adult and Child Lessons",
    },
    {
      img: "./src/assets/jelly.jpg",
      title: "Jelly the Jellyfish",
      description: "2-3 years",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "11:30",
      endTime: "12:00",
      price: "£16.00",
      colour: "violet",
      productColour: "emerald",
      productGroup: "Adult and Child Lessons",
    },
    {
      img: "./src/assets/crab.jpg",
      title: "Snappy the Crab",
      description: "18-24 months",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "12:00",
      endTime: "12:30",
      price: "£16.00",
      colour: "red",
      productColour: "emerald",
      productGroup: "Adult and Child Lessons",
    },
    {
      img: "./src/assets/starfish.jpg",
      title: "Twinkle The Starfish",
      description: "6-12 months",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "12:30",
      endTime: "13:00",
      price: "£16.00",
      colour: "pink",
      productColour: "emerald",
      productGroup: "Adult and Child Lessons",
    },
    {
      img: "./src/assets/seahorse.jpg",
      title: "Bubble the Seahorse",
      description: "12-18 months",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "13:15",
      endTime: "13:45",
      price: "£16.00",
      colour: "indigo",
      productColour: "emerald",
      productGroup: "Adult and Child Lessons",
    },
    {
      img: "./src/assets/Clown.jpg",
      title: "Carl the Clownfish",
      description: "3-6 months",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "13:45",
      endTime: "14:15",
      price: "£16.00",
      colour: "orange",
      productColour: "emerald",
      productGroup: "Adult and Child Lessons",
    },
    {
      img: "./src/assets/jelly.jpg",
      title: "Jelly the Jellyfish",
      description: "2-3 years",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "15:00",
      endTime: "15:30",
      price: "£16.00",
      colour: "violet",
      productColour: "emerald",
      productGroup: "Adult and Child Lessons",
    },
  ],
  Friday: [
    {
      img: "./src/assets/turtle.jpg",
      title: "Smiley the Turtle",
      description: "3-4 years",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "09:30",
      endTime: "10:00",
      price: "£16.00",
      colour: "emerald",
      productColour: "emerald",
      productGroup: "Adult and Child Lessons",
    },
    {
      img: "./src/assets/jelly.jpg",
      title: "Jelly the Jellyfish",
      description: "2-3 years",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "10:00",
      endTime: "10:30",
      price: "£16.00",
      colour: "violet",
      productColour: "emerald",
      productGroup: "Adult and Child Lessons",
    },
    {
      img: "./src/assets/jelly.jpg",
      title: "Jelly the Jellyfish",
      description: "2-3 years",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "10:30",
      endTime: "11:00",
      price: "£16.00",
      colour: "violet",
      productColour: "emerald",
      productGroup: "Adult and Child Lessons",
    },
    {
      img: "./src/assets/crab.jpg",
      title: "Snappy the Crab",
      description: "18-24 months",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "11:00",
      endTime: "11:30",
      price: "£16.00",
      colour: "red",
      productColour: "emerald",
      productGroup: "Adult and Child Lessons",
    },
    {
      img: "./src/assets/starfish.jpg",
      title: "Twinkle The Starfish",
      description: "6-12 months",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "12:00",
      endTime: "12:30",
      price: "£16.00",
      colour: "pink",
      productColour: "emerald",
      productGroup: "Adult and Child Lessons",
    },
    {
      img: "./src/assets/crab.jpg",
      title: "Snappy the Crab",
      description: "18-24 months",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "12:45",
      endTime: "13:15",
      price: "£16.00",
      colour: "red",
      productColour: "emerald",
      productGroup: "Adult and Child Lessons",
    },
  ],
  Saturday: [
    {
      img: "./src/assets/dolphin.jpg",
      title: "Danny the Dolphin (SEND)",
      description: "4-5 years",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "15:00",
      endTime: "15:30",
      price: "£16.00",
      colour: "sky",
      productColour: "emerald",
      productGroup: "Adult and Child Lessons",
    },
    {
      img: "./src/assets/starfish.jpg",
      title: "Twinkle the Starfish",
      description: "6-12 months",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "16:00",
      endTime: "16:30",
      price: "£16.00",
      colour: "pink",
      productColour: "emerald",
      productGroup: "Adult and Child Lessons",
    },
  ],
  Sunday: [],
};

export const orgClassEvents = {
  Monday: [
    {
      img: "./src/assets/turtle.jpg",
      title: "Smiley the Turtle",
      description: "3-4 years",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "09:30",
      endTime: "10:00",
      price: "£16.00",
      colour: "emerald",
    },
    {
      img: "./src/assets/jelly.jpg",
      title: "Jelly the Jellyfish",
      description: "2-3 years",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "10:00",
      endTime: "10:30",
      price: "£16.00",
      colour: "violet",
    },
    {
      img: "./src/assets/jelly.jpg",
      title: "Jelly the Jellyfish",
      description: "2-3 years",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "10:30",
      endTime: "11:00",
      price: "£16.00",
      colour: "violet",
    },
    {
      img: "./src/assets/crab.jpg",
      title: "Snappy the Crab",
      description: "18-24 months",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "11:00",
      endTime: "11:30",
      price: "£16.00",
      colour: "red",
    },
    {
      img: "./src/assets/starfish.jpg",
      title: "Twinkle The Starfish",
      description: "6-12 months",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "12:00",
      endTime: "12:30",
      price: "£16.00",
      colour: "pink",
    },
    {
      img: "./src/assets/crab.jpg",
      title: "Snappy the Crab",
      description: "18-24 months",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "12:45",
      endTime: "13:15",
      price: "£16.00",
      colour: "red",
    },
  ],
  Tuesday: [
    {
      img: "./src/assets/seahorse.jpg",
      title: "Bubble the Seahorse",
      description: "12-18 months",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "11:30",
      endTime: "12:00",
      price: "£16.00",
      colour: "indigo",
    },
    {
      img: "./src/assets/dolphin.jpg",
      title: "Danny the Dolphin (SEND)",
      description: "4-5 years",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "17:30",
      endTime: "18:00",
      price: "£16.00",
      colour: "sky",
    },
    {
      img: "./src/assets/dolphin.jpg",
      title: "Danny the Dolphin (SEND)",
      description: "4-5 years",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "18:00",
      endTime: "18:30",
      price: "£16.00",
      colour: "sky",
    },
  ],
  Wednesday: [
    {
      img: "./src/assets/starfish.jpg",
      title: "Twinkle The Starfish",
      description: "6-12 months",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "09:00",
      endTime: "09:30",
      price: "£16.00",
      colour: "pink",
    },
    {
      img: "./src/assets/jelly.jpg",
      title: "Jelly the Jellyfish",
      description: "2-3 years",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "10:00",
      endTime: "10:30",
      price: "£16.00",
      colour: "violet",
    },
    {
      img: "./src/assets/starfish.jpg",
      title: "Twinkle The Starfish",
      description: "6-12 months",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "11:00",
      endTime: "11:30",
      price: "£16.00",
      colour: "pink",
    },
    {
      img: "./src/assets/seahorse.jpg",
      title: "Bubble the Seahorse",
      description: "12-18 months",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "11:30",
      endTime: "12:00",
      price: "£16.00",
      colour: "indigo",
    },
    {
      img: "./src/assets/starfish.jpg",
      title: "Twinkle The Starfish",
      description: "6-12 months",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "14:30",
      endTime: "15:00",
      price: "£16.00",
      colour: "pink",
    },
    {
      img: "./src/assets/crab.jpg",
      title: "Snappy the Crab",
      description: "18-24 months",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "15:00",
      endTime: "15:30",
      price: "£16.00",
      colour: "red",
    },
  ],
  Thursday: [
    {
      img: "./src/assets/jelly.jpg",
      title: "Jelly the Jellyfish",
      description: "2-3 years",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "10:00",
      endTime: "10:30",
      price: "£16.00",
      colour: "violet",
    },
    {
      img: "./src/assets/Clown.jpg",
      title: "Carl the Clownfish",
      description: "3-6 months",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "10:30",
      endTime: "11:00",
      price: "£16.00",
      colour: "orange",
    },
    {
      img: "./src/assets/seahorse.jpg",
      title: "Bubble the Seahorse",
      description: "12-18 months",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "11:00",
      endTime: "11:30",
      price: "£16.00",
      colour: "indigo",
    },
    {
      img: "./src/assets/jelly.jpg",
      title: "Jelly the Jellyfish",
      description: "2-3 years",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "11:30",
      endTime: "12:00",
      price: "£16.00",
      colour: "violet",
    },
    {
      img: "./src/assets/crab.jpg",
      title: "Snappy the Crab",
      description: "18-24 months",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "12:00",
      endTime: "12:30",
      price: "£16.00",
      colour: "red",
    },
    {
      img: "./src/assets/starfish.jpg",
      title: "Twinkle The Starfish",
      description: "6-12 months",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "12:30",
      endTime: "13:00",
      price: "£16.00",
      colour: "pink",
    },
    {
      img: "./src/assets/seahorse.jpg",
      title: "Bubble the Seahorse",
      description: "12-18 months",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "13:15",
      endTime: "13:45",
      price: "£16.00",
      colour: "indigo",
    },
    {
      img: "./src/assets/Clown.jpg",
      title: "Carl the Clownfish",
      description: "3-6 months",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "13:45",
      endTime: "14:15",
      price: "£16.00",
      colour: "orange",
    },
    {
      img: "./src/assets/jelly.jpg",
      title: "Jelly the Jellyfish",
      description: "2-3 years",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "15:00",
      endTime: "15:30",
      price: "£16.00",
      colour: "violet",
    },
  ],
  Friday: [
    {
      img: "./src/assets/turtle.jpg",
      title: "Smiley the Turtle",
      description: "3-4 years",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "09:30",
      endTime: "10:00",
      price: "£16.00",
      colour: "emerald",
    },
    {
      img: "./src/assets/jelly.jpg",
      title: "Jelly the Jellyfish",
      description: "2-3 years",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "10:00",
      endTime: "10:30",
      price: "£16.00",
      colour: "violet",
    },
    {
      img: "./src/assets/jelly.jpg",
      title: "Jelly the Jellyfish",
      description: "2-3 years",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "10:30",
      endTime: "11:00",
      price: "£16.00",
      colour: "violet",
    },
    {
      img: "./src/assets/crab.jpg",
      title: "Snappy the Crab",
      description: "18-24 months",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "11:00",
      endTime: "11:30",
      price: "£16.00",
      colour: "red",
    },
    {
      img: "./src/assets/starfish.jpg",
      title: "Twinkle The Starfish",
      description: "6-12 months",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "12:00",
      endTime: "12:30",
      price: "£16.00",
      colour: "pink",
    },
    {
      img: "./src/assets/crab.jpg",
      title: "Snappy the Crab",
      description: "18-24 months",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "12:45",
      endTime: "13:15",
      price: "£16.00",
      colour: "red",
    },
  ],
  Saturday: [
    {
      img: "./src/assets/dolphin.jpg",
      title: "Danny the Dolphin (SEND)",
      description: "4-5 years",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "15:00",
      endTime: "15:30",
      price: "£16.00",
      colour: "sky",
    },
    {
      img: "./src/assets/starfish.jpg",
      title: "Twinkle the Starfish",
      description: "6-12 months",
      link: "/BubbleTheSeahorse",
      address: "Little Thetford",
      startTime: "16:00",
      endTime: "16:30",
      price: "£16.00",
      colour: "pink",
    },
  ],
  Sunday: [],
};
